let backend=null,notes={current:null,canvas:null,ctx:null,dirty:false,color:"#111111",size:3,tool:"pen"};
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));

function parseJson(raw,fallback,label){try{return JSON.parse(raw)}catch(error){console.error("Digi received invalid JSON from "+label,error);return fallback}}
function call(name,args,cb){if(backend)backend[name](...(args||[]),cb||function(){});}
function showStartupError(message){$("hint").textContent="Digi could not start safely.";$("results").innerHTML='<div class="empty"><strong>Digi needs assistance to start.</strong><br><br>'+esc(message||"A required application data item is missing or invalid.")+'<br><br>Digi has not automatically moved, deleted, or repaired your existing data. Do not rename or delete data folders to try to fix this. Visit the official Digi website for troubleshooting, or contact Digi support if you cannot resolve the problem.</div>';$("count").textContent="Unavailable";}
function showPreview(path,name,card){
document.querySelectorAll(".result.is-selected").forEach(el=>el.classList.remove("is-selected"));
if(card)card.classList.add("is-selected");
const panel=$("preview-panel");
panel.innerHTML='<div class="preview-loading"><span class="preview-spinner"></span><strong>Preparing preview</strong><p>'+esc(name)+'</p></div>';
call("previewFile",[path],raw=>{
const data=parseJson(raw,null,"document preview");
if(!data){panel.innerHTML='<div class="preview-empty"><strong>Preview unavailable</strong><p>Digi could not read the preview response.</p></div>';return}
if(data.kind==="error"){panel.innerHTML='<div class="preview-empty"><strong>Preview unavailable</strong><p>'+esc(data.message||"This file cannot be previewed.")+'</p><button class="small-button" id="preview-open">Open in app</button></div>';const b=$("preview-open");if(b)b.onclick=()=>call("openFile",[path]);return}
if(data.kind==="word"){
panel.innerHTML='<div class="preview-head"><div><span class="preview-type">WORD DOCUMENT</span><strong>'+esc(data.name||name)+'</strong></div><button class="small-button" id="preview-open">Open</button></div><div class="word-preview">'+(data.html||"")+'</div>';
const b=$("preview-open");if(b)b.onclick=()=>call("openFile",[path]);return;
}
if(data.kind==="pdf"){
panel.innerHTML='<div class="preview-head"><div><span class="preview-type">PDF DOCUMENT</span><strong>'+esc(data.name||name)+'</strong><small>'+esc(String(data.total||0))+' pages</small></div><button class="small-button" id="preview-open">Open</button></div><div class="pdf-preview">'+(data.pages||[]).map(p=>'<figure class="pdf-page"><img alt="Page '+esc(p.number)+'" src="'+p.image+'"><figcaption>Page '+esc(p.number)+'</figcaption></figure>').join("")+(data.truncated?'<p class="preview-note">Showing the first 20 pages. Open the document to view the rest.</p>':"")+'</div>';
const b=$("preview-open");if(b)b.onclick=()=>call("openFile",[path]);return;
}
panel.innerHTML='<div class="preview-empty"><strong>Preview unavailable</strong><p>This document format is not supported.</p></div>';
});
}
function refresh(){let q=$("search").value.trim();if(!q){$("results").innerHTML='<div class="empty">Type a search term to show files.</div>';$("count").textContent="0 results";$("preview-panel").innerHTML='<div class="preview-empty"><span class="preview-empty-icon">▤</span><strong>Document preview</strong><p>Select a search result to view it here.</p></div>';return}
call("search",[q,$("type").value,$("status").value,$("source").value,$("method").value,$("sort").value],raw=>{let rows=parseJson(raw,null,"search results");if(!Array.isArray(rows)){$("results").innerHTML='<div class="empty">Digi could not read search results. Check the startup log.</div>';$("count").textContent="Unavailable";return}$("count").textContent=rows.length+" result(s)";$("results").innerHTML=rows.length?rows.map(r=>'<article class="result" tabindex="0" role="button" aria-label="Preview '+esc(r.name)+'" data-preview="'+esc(r.path)+'" data-name="'+esc(r.name)+'"><div class="result-name">'+esc(r.name)+'</div><div class="result-meta">'+esc(r.path)+' · '+esc(r.ext)+' · '+(r.pages||0)+' pages · '+esc(r.status)+'</div><div class="result-actions"><button class="small-button" data-open="'+esc(r.path)+'">Open</button><button class="small-button" data-folder="'+esc(r.path)+'">Folder</button><button class="small-button" data-convert="'+esc(r.path)+'" data-kind="'+(r.ext===".pdf"?"word":"pdf")+'">'+(r.ext===".pdf"?"→ Word":"→ PDF")+'</button></div></article>').join(""):'<div class="empty">No matching files.</div>';
document.querySelectorAll("[data-preview]").forEach(card=>{const select=()=>showPreview(card.dataset.preview,card.dataset.name,card);card.onclick=e=>{if(e.target.closest("button"))return;select()};card.onkeydown=e=>{if((e.key==="Enter"||e.key===" ")&&!e.target.closest("button")){e.preventDefault();select()}};});
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=e=>{e.stopPropagation();call("openFile",[b.dataset.open])});document.querySelectorAll("[data-folder]").forEach(b=>b.onclick=e=>{e.stopPropagation();call("openFolder",[b.dataset.folder])});document.querySelectorAll("[data-convert]").forEach(b=>b.onclick=e=>{e.stopPropagation();startConversion(b)});});}
function conversionButton(path){return [...document.querySelectorAll("[data-convert]")].find(b=>b.dataset.convert===path);}
function startConversion(button){if(button.disabled)return;button.disabled=true;button.classList.add("conversion-active");button.dataset.original=button.textContent;button.innerHTML='<span class="conversion-label">0%</span><span class="conversion-track"><span class="conversion-fill"></span></span>';call("convert",[button.dataset.convert,button.dataset.kind],ok=>{if(ok===false)finishConversion(button,false,"Conversion could not be started.");});}
function finishConversion(button,success,message){if(!button)return;if(!success){button.disabled=false;button.classList.remove("conversion-active");button.textContent=button.dataset.original||"Convert";if(message)alert("Conversion failed: "+message);return}button.disabled=true;button.classList.remove("conversion-active");button.classList.add("conversion-success");button.innerHTML='<span class="success-check">✓</span> Success';setTimeout(()=>{button.classList.add("conversion-fading");setTimeout(()=>{button.classList.remove("conversion-success","conversion-fading");button.disabled=false;button.textContent=button.dataset.original||"Convert";refresh()},350)},3000);}

function modal(title,body){let m=$("modal");m.classList.remove("hidden");m.innerHTML='<div class="modal-card"><div class="modal-head"><b>'+esc(title)+'</b><button class="ui-button" id="close-modal">Close</button></div><div class="modal-body">'+body+'</div></div>';$("close-modal").onclick=()=>m.classList.add("hidden");}
function openNotes(){modal("Digi Notes",'<div class="note-layout"><div class="note-tree" id="note-tree"></div><div class="note-canvas-wrap"><div class="note-toolbar"><button class="small-button" id="pen">Pen</button><button class="small-button" id="eraser">Eraser</button><input id="note-color" type="color" value="#111111"><input id="note-size" type="range" min="1" max="30" value="3"><button class="small-button" id="new-book">Notebook</button><button class="small-button" id="new-page">Page</button><button class="small-button" id="save-note">Save</button></div><canvas id="note-canvas" class="note-canvas" width="1100" height="650"></canvas></div></div>');
$("pen").onclick=()=>notes.tool="pen";$("eraser").onclick=()=>notes.tool="eraser";$("note-color").oninput=e=>notes.color=e.target.value;$("note-size").oninput=e=>notes.size=+e.target.value;$("new-book").onclick=()=>{let n=prompt("Notebook name");if(n)call("createNotebook",["",n],loadNotes)};$("new-page").onclick=()=>{if(!notes.current)return alert("Select a notebook first.");let n=prompt("Page name");if(n)call("createNotePage",[notes.current,n],p=>{notes.current=p;setupCanvas();loadNotes()})};$("save-note").onclick=saveNote;setupCanvas();loadNotes();}
function setupCanvas(){let c=$("note-canvas");if(!c)return;notes.canvas=c;notes.ctx=c.getContext("2d");notes.ctx.fillStyle="#fff";notes.ctx.fillRect(0,0,c.width,c.height);let down=false,last=null,pos=e=>{let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.onpointerdown=e=>{if(e.pointerType==="touch")return;down=true;last=pos(e);c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!down)return;let p=pos(e),x=notes.ctx; x.beginPath();x.moveTo(last.x,last.y);x.lineTo(p.x,p.y);x.strokeStyle=notes.tool==="eraser"?"#fff":notes.color;x.lineWidth=notes.tool==="eraser"?notes.size*4:notes.size;x.lineCap="round";x.stroke();last=p;notes.dirty=true};c.onpointerup=()=>{down=false;last=null};c.onpointercancel=()=>{down=false};}
function loadNotes(){call("notesTree",[],raw=>{let tree=parseJson(raw,null,"notes tree"),el=$("note-tree");if(!el)return;if(!Array.isArray(tree)){el.textContent="Notes could not be loaded.";return}el.innerHTML="";let walk=(items,d)=>items.forEach(x=>{let b=document.createElement("button");b.className="small-button";b.style.display="block";b.style.margin="0 0 5px "+(d*10)+"px";b.textContent=(x.type==="folder"?"▣ ":"▤ ")+x.name;b.onclick=()=>{notes.current=x.path;if(x.type==="page")call("loadNote",[x.path],loadData)};el.appendChild(b);if(x.children)walk(x.children,d+1)});walk(tree,0)});}
function loadData(data){let img=new Image();img.onload=()=>{let c=notes.canvas;c.width=Math.max(1100,img.width);c.height=Math.max(650,img.height);notes.ctx.drawImage(img,0,0);notes.dirty=false};img.src=data;}
function saveNote(){if(notes.current&&notes.canvas)call("saveNote",[notes.current,notes.canvas.toDataURL("image/png")],()=>notes.dirty=false);}
$("window-minimize").onclick=()=>call("minimizeWindow");$("window-maximize").onclick=()=>{document.documentElement.classList.toggle("window-maximized");call("toggleMaximizeWindow");};$("window-close").onclick=()=>call("closeWindow");
const filtersToggle=$("filters-toggle");if(filtersToggle){filtersToggle.onclick=()=>{const open=document.body.classList.toggle("filters-open");filtersToggle.setAttribute("aria-expanded",String(open));filtersToggle.title=open?"Hide filters":"Show filters";const icon=filtersToggle.querySelector(".filters-toggle-icon");if(icon)icon.textContent=open?"‹":"›";};}
$("search").oninput=()=>{if(!$("search").value.trim())document.body.classList.remove("filters-open");refresh();};$("clear").onclick=()=>{$("search").value="";refresh()};["type","status","source","method","sort"].forEach(id=>$(id).onchange=refresh);$("scan").onclick=()=>call("scan");$("home-notes").onclick=openNotes;$("home-wiki").onclick=()=>modal("Digi Wiki",'<div class="feature-coming"><span class="feature-coming-icon">▤</span><h2>Wiki is coming soon</h2><p>Your knowledge workspace is planned for a future Digi update.</p></div>');$("repository").onclick=()=>call("chooseLibraryFolder",[],p=>{if(p)call("setLibraryFolder",[p],refresh)});$("incoming").onclick=()=>call("chooseIncomingFolder",[],p=>{if(p)alert("Incoming: "+p)});$("recent").onclick=()=>call("recentSearches",[],raw=>{let recent=parseJson(raw,[],"recent searches");modal("Recent searches",Array.isArray(recent)?recent.map(esc).join("<br>")||"None":"Recent searches could not be loaded.")});
new QWebChannel(qt.webChannelTransport,ch=>{backend=ch.objects.backend;window.digiBackend=backend;backend.releaseManifestResult.connect(raw=>window.dispatchEvent(new CustomEvent("digi-release-manifest",{detail:raw})));backend.indexUpdated.connect(refresh);backend.conversionProgress.connect((path,value)=>{let b=conversionButton(path);if(!b)return;let label=b.querySelector(".conversion-label"),fill=b.querySelector(".conversion-fill");if(label)label.textContent=value+"%";if(fill)fill.style.width=value+"%";});backend.conversionFinished.connect((ok,msg,path)=>{finishConversion(conversionButton(path),ok,msg);});backend.error.connect(console.error);backend.state(raw=>{
let state=parseJson(raw,null,"startup state");if(!state){showStartupError("Digi could not read its startup state.");return}
if(state.ready){refresh();return}
backend.recalibrateVersion(ok=>{
if(ok){backend.state(updated=>{let next=parseJson(updated,null,"updated startup state");if(!next){showStartupError("Digi could not read its startup state.");return}if(next.ready){$("hint").textContent="Type a search term to show files.";refresh()}else showStartupError(next.version_problem||"Backend services could not be initialised.")})}
else showStartupError(state.version_problem||"Digi could not initialise its backend.")
});
});});
